development:
  adapter: postgresql
  encoding: utf8
  database: reservation_react_development
  pool: 5
  username: postgres
  password: Security1993@hello.1

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: reservation_react_test
  pool: 5
  username: postgres
  password: Security1993@hello.1

production:
  adapter: postgresql
  encoding: utf8
  database: reservation_react_production
  pool: 5
  username: 
  password: 

cucumber:
  <<: *TEST
